version: '3'
services:
  node-1:
    image: cube2222/raft
    ports:
      - 3000:8002
    networks:
      - cluster
    environment:
      RAFT_CLUSTERADDRESSES: "node-2,node-3"
  node-2:
    image: cube2222/raft
    ports:
      - 3001:8002
    networks:
      - cluster
    environment:
      RAFT_CLUSTERADDRESSES: "node-1,node-3"
  node-3:
    image: cube2222/raft
    ports:
      - 3002:8002
    networks:
      - cluster
    environment:
      RAFT_CLUSTERADDRESSES: "node-1,node-2"
networks:
  cluster: