// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

/*
Package raft is a generated protocol buffer package.

It is generated from these files:
	raft.proto

It has these top-level messages:
	Entry
	AppendEntriesRequest
	AppendEntriesResponse
	RequestVoteRequest
	RequestVoteResponse
	EntryResponse
*/
package raft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entry struct {
	ID   string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Term int64  `protobuf:"varint,3,opt,name=term" json:"term,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entry) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Entry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Entry) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

type AppendEntriesRequest struct {
	Term         int64  `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	LeaderID     string `protobuf:"bytes,2,opt,name=leaderID" json:"leaderID,omitempty"`
	PrevLogIndex int64  `protobuf:"varint,3,opt,name=prevLogIndex" json:"prevLogIndex,omitempty"`
	PrevLogTerm  int64  `protobuf:"varint,4,opt,name=prevLogTerm" json:"prevLogTerm,omitempty"`
	Entry        *Entry `protobuf:"bytes,5,opt,name=entry" json:"entry,omitempty"`
	LeaderCommit int64  `protobuf:"varint,6,opt,name=leaderCommit" json:"leaderCommit,omitempty"`
}

func (m *AppendEntriesRequest) Reset()                    { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()               {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppendEntriesRequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRequest) GetLeaderID() string {
	if m != nil {
		return m.LeaderID
	}
	return ""
}

func (m *AppendEntriesRequest) GetPrevLogIndex() int64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogTerm() int64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesRequest) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *AppendEntriesRequest) GetLeaderCommit() int64 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type AppendEntriesResponse struct {
	Term    int64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Success bool  `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *AppendEntriesResponse) Reset()                    { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()               {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AppendEntriesResponse) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RequestVoteRequest struct {
	Term         int64  `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	CandidateID  string `protobuf:"bytes,2,opt,name=candidateID" json:"candidateID,omitempty"`
	LastLogIndex int64  `protobuf:"varint,3,opt,name=lastLogIndex" json:"lastLogIndex,omitempty"`
	LastLogTerm  int64  `protobuf:"varint,4,opt,name=lastLogTerm" json:"lastLogTerm,omitempty"`
}

func (m *RequestVoteRequest) Reset()                    { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()               {}
func (*RequestVoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RequestVoteRequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRequest) GetCandidateID() string {
	if m != nil {
		return m.CandidateID
	}
	return ""
}

func (m *RequestVoteRequest) GetLastLogIndex() int64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteRequest) GetLastLogTerm() int64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	Term        int64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	VoteGranted bool  `protobuf:"varint,2,opt,name=voteGranted" json:"voteGranted,omitempty"`
}

func (m *RequestVoteResponse) Reset()                    { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()               {}
func (*RequestVoteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RequestVoteResponse) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteResponse) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

type EntryResponse struct {
}

func (m *EntryResponse) Reset()                    { *m = EntryResponse{} }
func (m *EntryResponse) String() string            { return proto.CompactTextString(m) }
func (*EntryResponse) ProtoMessage()               {}
func (*EntryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*Entry)(nil), "raft.Entry")
	proto.RegisterType((*AppendEntriesRequest)(nil), "raft.AppendEntriesRequest")
	proto.RegisterType((*AppendEntriesResponse)(nil), "raft.AppendEntriesResponse")
	proto.RegisterType((*RequestVoteRequest)(nil), "raft.RequestVoteRequest")
	proto.RegisterType((*RequestVoteResponse)(nil), "raft.RequestVoteResponse")
	proto.RegisterType((*EntryResponse)(nil), "raft.EntryResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Raft service

type RaftClient interface {
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
	NewEntry(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*EntryResponse, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := grpc.Invoke(ctx, "/raft.Raft/AppendEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	out := new(RequestVoteResponse)
	err := grpc.Invoke(ctx, "/raft.Raft/RequestVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) NewEntry(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*EntryResponse, error) {
	out := new(EntryResponse)
	err := grpc.Invoke(ctx, "/raft.Raft/NewEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Raft service

type RaftServer interface {
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
	NewEntry(context.Context, *Entry) (*EntryResponse, error)
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.Raft/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.Raft/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_NewEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).NewEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.Raft/NewEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).NewEntry(ctx, req.(*Entry))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "raft.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _Raft_AppendEntries_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _Raft_RequestVote_Handler,
		},
		{
			MethodName: "NewEntry",
			Handler:    _Raft_NewEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0xcd, 0x40, 0xe1, 0x83, 0x5b, 0xf8, 0x4c, 0x06, 0x4d, 0x6a, 0xdd, 0xd4, 0xae, 0xba, 0x30,
	0x2c, 0xf0, 0x01, 0x8c, 0x0a, 0xd1, 0x46, 0xe3, 0x62, 0x62, 0xdc, 0x8f, 0xf4, 0x62, 0x48, 0xa4,
	0xad, 0x9d, 0x01, 0xf5, 0x2d, 0x7c, 0x26, 0x5f, 0xc1, 0x17, 0x32, 0xf3, 0x23, 0x0e, 0xd8, 0xb0,
	0x9b, 0x7b, 0xee, 0xc9, 0xb9, 0xf7, 0x9c, 0xde, 0x02, 0x54, 0x7c, 0x26, 0x87, 0x65, 0x55, 0xc8,
	0x82, 0x7a, 0xea, 0x1d, 0x9f, 0x41, 0x6b, 0x92, 0xcb, 0xea, 0x9d, 0xfe, 0x87, 0x46, 0x3a, 0x0e,
	0x48, 0x44, 0x92, 0x2e, 0x6b, 0xa4, 0x63, 0x4a, 0xc1, 0xcb, 0xb8, 0xe4, 0x41, 0x23, 0x22, 0x49,
	0x8f, 0xe9, 0xb7, 0xc2, 0x24, 0x56, 0x8b, 0xa0, 0x19, 0x91, 0xa4, 0xc9, 0xf4, 0x3b, 0xfe, 0x22,
	0xb0, 0x7f, 0x5e, 0x96, 0x98, 0x67, 0x4a, 0x67, 0x8e, 0x82, 0xe1, 0xcb, 0x12, 0x85, 0x5c, 0x93,
	0xc9, 0x2f, 0x99, 0x86, 0xd0, 0x79, 0x46, 0x9e, 0x61, 0x95, 0x8e, 0xb5, 0x70, 0x97, 0xad, 0x6b,
	0x1a, 0x43, 0xaf, 0xac, 0x70, 0x75, 0x5b, 0x3c, 0xa5, 0x79, 0x86, 0x6f, 0x76, 0xc8, 0x06, 0x46,
	0x23, 0xf0, 0x6d, 0x7d, 0xaf, 0xa4, 0x3d, 0x4d, 0x71, 0x21, 0x7a, 0x0c, 0x2d, 0x54, 0x7e, 0x82,
	0x56, 0x44, 0x12, 0x7f, 0xe4, 0x0f, 0xb5, 0x63, 0x6d, 0x91, 0x99, 0x8e, 0x1a, 0x64, 0x86, 0x5e,
	0x16, 0x8b, 0xc5, 0x5c, 0x06, 0x6d, 0x33, 0xc8, 0xc5, 0xe2, 0x09, 0x1c, 0x6c, 0x99, 0x12, 0x65,
	0x91, 0x0b, 0xac, 0x75, 0x15, 0xc0, 0x3f, 0xb1, 0x9c, 0x4e, 0x51, 0x08, 0x6d, 0xaa, 0xc3, 0x7e,
	0xca, 0xf8, 0x83, 0x00, 0xb5, 0x79, 0x3c, 0x14, 0x12, 0x77, 0x45, 0x13, 0x81, 0x3f, 0xe5, 0x79,
	0x36, 0xcf, 0xb8, 0xc4, 0x75, 0x3a, 0x2e, 0xa4, 0xf7, 0xe6, 0x42, 0x6e, 0x07, 0xe4, 0x62, 0x4a,
	0xc5, 0xd6, 0x6e, 0x40, 0x0e, 0x14, 0xdf, 0xc0, 0x60, 0x63, 0xa3, 0x1d, 0xbe, 0x22, 0xf0, 0x57,
	0x85, 0xc4, 0xab, 0x8a, 0xe7, 0x12, 0x33, 0xeb, 0xcd, 0x85, 0xe2, 0x3d, 0xe8, 0x9b, 0x68, 0xad,
	0xcc, 0xe8, 0x93, 0x80, 0xc7, 0xf8, 0x4c, 0xd2, 0x6b, 0xe8, 0x6f, 0x04, 0x48, 0x43, 0xf3, 0x25,
	0xea, 0x4e, 0x25, 0x3c, 0xaa, 0xed, 0xd9, 0xcd, 0x2e, 0xc0, 0x77, 0x16, 0xa6, 0x81, 0xe1, 0xfe,
	0x4d, 0x35, 0x3c, 0xac, 0xe9, 0x58, 0x8d, 0x13, 0xe8, 0xdc, 0xe1, 0xab, 0x39, 0x74, 0xf7, 0x24,
	0xc2, 0x81, 0x7b, 0x1f, 0x96, 0xfd, 0xd8, 0xd6, 0x3f, 0xc8, 0xe9, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x5d, 0x5e, 0xdf, 0x21, 0x2e, 0x03, 0x00, 0x00,
}
